Turin RAS enablement
AMDESE/amd-bmc-ras pull request #68
Opened 2023-07-20 14:04 UTC by abinayaddhandapani

1. Enable runtime error polling for MCA, DRAM CECC and PCIE errors.
2. Reorganise the code and move the functionalities to specific cpp files
3. Add new DEBUG_LOG_ID's for the Turin platform
4. Trigger cold reset via RSMRST toggling
5. Support to download CPER files via redfish for runtime and fatal errors

2023-07-24 23:41 UTC, supven01 requested changes
The re-organization looks much better now especially the configuration.hpp and configuration.cpp.
There are still enormous files like main.cpp and fatal_error.cpp which needs to be refactored after 06 Turin release.

2023-07-24 23:41 UTC, supven01 commented on inc/cper.hpp
> +  char                               FRUText[20];
nit: tab used instead of spaces or vice versa

2023-07-25 09:20 UTC, abinayaddhandapani commented on inc/write_cper_data.hpp
> +#include "ras.hpp"
defenitions in write_cper_data.hpp is moved to write_cper_data.cpp file. write_cper_data.hpp is no longer needed and is check-in by mistake. Will delete this file and push the code again

2023-07-25 13:25 UTC, abinayaddhandapani commented on inc/Config.hpp
> +{
Ack

2023-07-25 13:29 UTC, abinayaddhandapani commented on service_files/com.amd.crashdump.service
> +ExecStartPre=/bin/sleep 5
When the application is restarted due to any crash, without the sleep , the service is throwing error as "Service start request repeated too quickly, refusing to start limit"

2023-07-25 13:30 UTC, abinayaddhandapani commented on inc/cper.hpp
> +  char                               FRUText[20];
Ack

2023-07-25 13:30 UTC, abinayaddhandapani commented on inc/cper.hpp
>    uint32_t                           Reserved[96];
Ack

2023-07-25 13:30 UTC, abinayaddhandapani commented on inc/cper_runtime.hpp
> +    uint8_t                Capability[60];
Ack

2023-07-25 13:30 UTC, abinayaddhandapani commented on CMakeLists.txt
> +              src/dbus.cpp
Ack

2023-07-25 23:28 UTC, supven01 approved these changes

2023-07-26 04:52 UTC, merged