Move from CMake to Meson build
AMDESE/amd-bmc-ras pull request #74
Opened 2023-09-05 14:13 UTC by abinayaddhandapani

Move compilation from CMake to meson build.
format the code using clang-format
Remove unused header files included in compilation

2023-09-05 20:40 UTC, supven01 requested changes
Add a verbose commit message to indicate what all changes were done. I am pretty sure its more than just the move from CMake to Meson build

2023-09-05 20:40 UTC, supven01 commented on src/Config.cpp
> +    {{"P1_DIMM_A", "null"},  {"P1_DIMM_A1", "null"}, {"P1_DIMM_B", "null"},
Why the wrap around?

2023-09-05 20:40 UTC, supven01 commented on src/Config.cpp
> +     {"P1_DIMM_B1", "null"}, {"P1_DIMM_C", "null"},  {"P1_DIMM_C1", "null"},
Why the wrap around?

2023-09-06 04:32 UTC, abinayaddhandapani commented on src/Config.cpp
> +    {{"P1_DIMM_A", "null"},  {"P1_DIMM_A1", "null"}, {"P1_DIMM_B", "null"},
The clang formatter has formatted the P0_DimmLabels

2023-09-06 04:32 UTC, abinayaddhandapani commented on src/Config.cpp
> +     {"P1_DIMM_B1", "null"}, {"P1_DIMM_C", "null"},  {"P1_DIMM_C1", "null"},
The clang formatter has formatted the P1_DimmLabels

2023-09-15 14:22 UTC, supven01 commented on src/Config.cpp
> +    {{"P1_DIMM_A", "null"},  {"P1_DIMM_A1", "null"}, {"P1_DIMM_B", "null"},
ok.

2023-09-15 14:24 UTC, merged