Increase the Set Ras Oob Config retries
AMDESE/amd-bmc-ras pull request #76
Opened 2023-11-20 04:12 UTC by abinayaddhandapani

Increasing the SetRasOobConfig retries to 15 minutes as the 2P systems take more time to enable PCIE AER

2023-11-20 16:20 UTC, mahkurap commented on src/runtime_errors.cpp
> +        sleep(INDEX_20);
I am not sure why INDEX_20 is used here? INDEX_20 is offset in the PPR record for a different purpose.  I dont think we should reuse that macro here.  May be we can define a new macro for 20 seconds and use it, it improves the readability of the program. 

struct error_section_descriptor
{
    uint32_t SectionOffset;
    uint32_t SectionLength;
    uint8_t RevisionMinor;
    uint8_t RevisionMajor;
    uint8_t SecValidMask;
    uint8_t Reserved;
    uint32_t SectionFlags;
    GUID_T SectionType;
    uint64_t FRUId[INDEX_2];
    uint32_t Severity;
    char FRUText[INDEX_20];
} __attribute__((packed));

2023-11-20 16:20 UTC, mahkurap commented on src/runtime_errors.cpp
> +    uint16_t retryCount = 45;
how about increasing only the retryCount and keeping the sleep to 10 seconds.  That way, we are polling 10 more times, we will be quicker to respond back.  Also aren't we changing the behavior for single processor system by sleeping for longer time?

2023-11-21 04:43 UTC, abinayaddhandapani commented on src/runtime_errors.cpp
> +    uint16_t retryCount = 45;
Hi Mahesh. We are sending SetRasOobConfig command every 20 second until the command succeeds. Once the command is successful, the module starts the RAS functionality. For 1P system it takes around 180 seconds (9 retries for every 20 seconds ) and 600 seconds for 2P system (Around 30 retries for every 20 seconds) for the command to be successful. As it takes anywhere from 3 to 15 minutes for the PCIE AER to be enabled , I have used retries for every 20 seconds.

2023-11-22 09:10 UTC, rajaganeshr commented on src/runtime_errors.cpp
> +    uint16_t retryCount = 45;
Please test this once on dense platforms as well. init might be a factor of number of cores in soc.

2023-11-28 11:25 UTC, abinayaddhandapani commented on src/runtime_errors.cpp
> +    uint16_t retryCount = 45;
As per discussion with Mahesh, sleep of 20 seconds will not have any functional impact for both 1P and 2P system. So retaining the code changes of sleep 20.

2023-11-28 15:03 UTC, mahkurap approved these changes

2023-11-28 15:59 UTC, supven01 requested changes

2023-11-28 15:59 UTC, supven01 commented on src/runtime_errors.cpp
> +        retryCount = 45;
nit: magic number 45.

2023-11-29 06:00 UTC, abinayaddhandapani commented on src/runtime_errors.cpp
> +    uint16_t retryCount = 45;
@rajaganeshr It is verified on dense platform as well

2023-11-29 13:57 UTC, supven01 approved these changes

2023-11-29 13:57 UTC, merged