Add support for fatal error monitoring
AMDESE/amd-bmc-ras pull request #98
Opened 2024-11-13 16:13 UTC by abinayaddhandapani

- The application monitors APML_ALERT_L and upon assertion of the
      GPIO PIN , BMC collects the MCA MSR dump and creates CPER record.

    - Depending on the user configuration , the application initiates
      system recovery.

    - ras-config.json contains the configuration parameters with
      default value. User can get and set the configuration parameters
      using d-bus calls to the methods getAttribute and setAttribute.

    - The application also contains harvesting of last transaction address,
      debug log ID's.

    - The application is intended to be supported for 1P and 2P platforms.
    
    Tested fields:
    
    Tested in sp5 platform
    
    root@sp5:/var/lib/amd-ras# ls
current_index    ras-error0.cper  ras-error2.cper  ras-error4.cper  ras-error6.cper  ras-error8.cper
ras-config.json  ras-error1.cper  ras-error3.cper  ras-error5.cper  ras-error7.cper  ras-error9.cper
root@sp5:/var/lib/amd-ras# hexdump -C ras-error0.cper
00000000  43 50 45 52 00 01 ff ff  ff ff 02 00 01 00 00 00  |CPER............|
00000010  03 00 00 00 10 01 02 00  07 1a 11 01 0f 0b 18 15  |................|
00000020  01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  ac 3f fa 61 80 cb 92 42  8b fb d6 43 b1 de 17 f4  |.?.a...B...C....|
00000050  fe 6f f5 e8 9c 91 c5 4c  ba 88 65 ab e1 49 13 bb  |.o.....L..e..I..|
00000060  01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  10 01 00 00 00 00 01 00  01 11 03 00 01 00 00 00  |................|
00000090  78 0c ac 32 23 26 f6 48  b0 d0 73 65 72 5f d6 ae  |x..2#&.H..ser_..|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000b0  01 00 00 00 50 30 00 00  00 00 00 00 00 00 00 00  |....P0..........|
000000c0  00 00 00 00 00 00 00 00  10 01 01 00 00 00 01 00  |................|
000000d0  01 11 03 00 01 00 00 00  78 0c ac 32 23 26 f6 48  |........x..2#&.H|
000000e0  b0 d0 73 65 72 5f d6 ae  00 00 00 00 00 00 00 00  |..ser_..........|
000000f0  00 00 00 00 00 00 00 00  01 00 00 00 50 31 00 00  |............P1..|
00000100  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000110  07 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000120  11 00 00 00 0b 00 ff 00  00 00 00 00 00 00 00 00  |................|
00000130  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000150  e0 00 00 4d 00 00 00 00  00 70 b1 13 18 00 00 00  |...M.....p......|
00000160  0b 01 00 00 00 00 a0 ba  00 00 00 00 00 00 00 00  |................|
00000170  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000190  01 00 80 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001a0  3f 00 00 00 00 00 00 00  0b 01 00 00 00 00 a0 ba  |?...............|
000001b0  00 00 00 00 00 00 00 00  00 00 00 00 f6 0f 0c d0  |................|
000001c0  fd 01 00 00 27 00 00 00  00 70 b1 13 18 00 00 00  |....'....p......|
000001d0  e0 00 00 4d 00 00 00 00  00 00 00 00 00 00 00 00  |...M............|
000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00020110

2024-11-18 16:51 UTC, ojayanth commented
@abinayaddhandapani  Can you run ./../openbmc-build-scripts/scripts/format-code.sh tool . In your devbox you can do docker setup and run this tool from docker.

2024-11-18 17:45 UTC, ojayanth commented
amd-bmc-ras$ ./../openbmc-build-scripts/scripts/format-code.sh
    Formatting code under /mnt/work2/ojayanth/Code/amd-bmc-ras
    clang_format: cannot find config .clang-format
    eslint: cannot find .eslintrc.json; using /mnt/work2/ojayanth/Code/openbmc-build-scripts/config/eslint-global-config.json
    markdownlint: cannot find .markdownlint.yaml; using /mnt/work2/ojayanth/Code/openbmc-build-scripts/config/markdownlint.yaml
    prettier: cannot find .prettierrc.yaml; using /mnt/work2/ojayanth/Code/openbmc-build-scripts/config/prettierrc.yaml
    Running commit_gitlint
-: UC1 Line exceeds max length (96>72).
    It's possible you intended to use one of the following exceptions:
    1. Put logs or shell script in a quoted section with triple quotes (''')
        before and after the section
    2. Put a long link at the bottom in a footnote.
        example: [1] https://my_long_link.com
    Line that was too long:
: "NAME                                TYPE      SIGNATURE RESULT/VALUE                       FLAGS"
    Running commit_spelling
codespell-dictionary - misspelling count >> 0
generic-dictionary - misspelling count >> 0
    Running eslint
    Running markdownlint
README.md:1:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "#AMD BMC RAS"]
README.md:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "#AMD BMC RAS"]
    Failed markdownlint; temporarily ignoring.
    Running prettier
config/ras-config.json 49ms
README.md 23ms
commit_gitlint: FAILED

2024-11-18 18:02 UTC, ojayanth commented
@abinayaddhandapani Direction on Header file inclusion:  
- Including headers directly in the source file makes it clear which dependencies are needed for that specific file. This improves readability and maintainability.
- Relying on another header file to include necessary headers can lead to hidden dependencies, making the codebase harder to understand and maintain. Direct inclusion avoids this issue.
Please add header files, which is necessary for the specific source file, 
 Example : inc/ras.hpp add boot dependency and not used anywhere in the header. .

Refer https://github.com/openbmc/docs/blob/master/cpp-style-and-conventions.md for more details.

2024-11-19 14:51 UTC, abinayaddhandapani commented
> @abinayaddhandapani Can you please run ./../openbmc-build-scripts/scripts/format-code.sh tool . In your devbox you can do docker setup and run this tool from docker.

@ojayanth  

adhandap@ebcc56e935b6:/mnt/work2/adhandap/Code/amd-bmc-ras$ ../openbmc-build-scripts/scripts/format-code.sh
Formatting code under /mnt/work2/adhandap/Code/amd-bmc-ras
eslint: cannot find .eslintrc.json; using /mnt/work2/adhandap/Code/openbmc-build-scripts/config/eslint-global-config.json
markdownlint: cannot find .markdownlint.yaml; using /mnt/work2/adhandap/Code/openbmc-build-scripts/config/markdownlint.yaml
prettier: cannot find .prettierrc.yaml; using /mnt/work2/adhandap/Code/openbmc-build-scripts/config/prettierrc.yaml
Running commit_gitlint
Running commit_spelling
codespell-dictionary - misspelling count >> 0
generic-dictionary - misspelling count >> 0
Running clang_format
Running eslint
Running markdownlint
Running prettier
config/ras-config.json 43ms (unchanged)
README.md 25ms (unchanged)
Result differences...
Format: PASSED

2024-11-19 14:52 UTC, abinayaddhandapani commented
> amd-bmc-ras$ ./../openbmc-build-scripts/scripts/format-code.sh Formatting code under /mnt/work2/ojayanth/Code/amd-bmc-ras clang_format: cannot find config .clang-format eslint: cannot find .eslintrc.json; using /mnt/work2/ojayanth/Code/openbmc-build-scripts/config/eslint-global-config.json markdownlint: cannot find .markdownlint.yaml; using /mnt/work2/ojayanth/Code/openbmc-build-scripts/config/markdownlint.yaml prettier: cannot find .prettierrc.yaml; using /mnt/work2/ojayanth/Code/openbmc-build-scripts/config/prettierrc.yaml Running commit_gitlint -: UC1 Line exceeds max length (96>72). It's possible you intended to use one of the following exceptions: 1. Put logs or shell script in a quoted section with triple quotes (''') before and after the section 2. Put a long link at the bottom in a footnote. example: [1] https://my_long_link.com Line that was too long: : "NAME TYPE SIGNATURE RESULT/VALUE FLAGS" Running commit_spelling codespell-dictionary - misspelling count >> 0 generic-dictionary - misspelling count >> 0 Running eslint Running markdownlint README.md:1:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "#AMD BMC RAS"] README.md:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "#AMD BMC RAS"] Failed markdownlint; temporarily ignoring. Running prettier config/ras-config.json 49ms README.md 23ms commit_gitlint: FAILED

@ojayanth  adhandap@ebcc56e935b6:/mnt/work2/adhandap/Code/amd-bmc-ras$ ../openbmc-build-scripts/scripts/format-code.sh
Formatting code under /mnt/work2/adhandap/Code/amd-bmc-ras
eslint: cannot find .eslintrc.json; using /mnt/work2/adhandap/Code/openbmc-build-scripts/config/eslint-global-config.json
markdownlint: cannot find .markdownlint.yaml; using /mnt/work2/adhandap/Code/openbmc-build-scripts/config/markdownlint.yaml
prettier: cannot find .prettierrc.yaml; using /mnt/work2/adhandap/Code/openbmc-build-scripts/config/prettierrc.yaml
Running commit_gitlint
Running commit_spelling
codespell-dictionary - misspelling count >> 0
generic-dictionary - misspelling count >> 0
Running clang_format
Running eslint
Running markdownlint
Running prettier
config/ras-config.json 43ms (unchanged)
README.md 25ms (unchanged)
Result differences...
Format: PASSED

2024-11-19 14:53 UTC, abinayaddhandapani commented
> @abinayaddhandapani Direction on Header file inclusion:
> 
> * Including headers directly in the source file makes it clear which dependencies are needed for that specific file. This improves readability and maintainability.
> * Relying on another header file to include necessary headers can lead to hidden dependencies, making the codebase harder to understand and maintain. Direct inclusion avoids this issue.
>   Please add header files, which is necessary for the specific source file,
>   Example : inc/ras.hpp add boot dependency and not used anywhere in the header. .
>   Some additional points also need to considering defining header file contents.
>   
>   * Create multiple headers based on the scope and responsibility of the code.
>   * One Header per Source File: Typically, each .cpp file should have a corresponding .h file. This makes it clear which declarations belong to which implementations and helps in managing dependencies.
> 
> Refer https://github.com/openbmc/docs/blob/master/cpp-style-and-conventions.md for more details.

@ojayanth Moved the header files to the corresponding source files instead of adding it in ras.hpp file.

2024-11-19 15:07 UTC, ojayanth requested changes
Review still in progress

2024-11-19 17:24 UTC, ojayanth commented on inc/ras.hpp
> +static const std::string RAS_DIR = "/var/lib/amd-ras/";
Move this as part of meson option , will help user to modify path if required. , and other varibales can define as exxtension of this

2024-11-19 17:32 UTC, ojayanth commented
> > @abinayaddhandapani Direction on Header file inclusion:
> > 
> > * Including headers directly in the source file makes it clear which dependencies are needed for that specific file. This improves readability and maintainability.
> > * Relying on another header file to include necessary headers can lead to hidden dependencies, making the codebase harder to understand and maintain. Direct inclusion avoids this issue.
> >   Please add header files, which is necessary for the specific source file,
> >   Example : inc/ras.hpp add boot dependency and not used anywhere in the header. .
> >   Some additional points also need to considering defining header file contents.
> >   
> >   * Create multiple headers based on the scope and responsibility of the code.
> >   * One Header per Source File: Typically, each .cpp file should have a corresponding .h file. This makes it clear which declarations belong to which implementations and helps in managing dependencies.
> > 
> > Refer https://github.com/openbmc/docs/blob/master/cpp-style-and-conventions.md for more details.
> 
> @ojayanth Moved the header files to the corresponding source files instead of adding it in ras.hpp file.

Still seeing lot of unused constants varible definition in the commit some  
 can you review these variables , and keep usage specific , unless there is strong reason for keeping everything at one place.
Also keep the variable/constants only used by this commit .

2024-11-20 03:11 UTC, ojayanth commented
@abinayaddhandapani  please run format-code.sh commit specific and strt fixing format issues specific to commit . Also move clang cofig file before adding source code commit.

2024-11-20 09:10 UTC, ojayanth requested changes

2024-11-20 09:10 UTC, ojayanth commented on inc/ras.hpp
> +static const int RESERVED = 0;
Scoped Enums: based constants  for same types: use enum class to create scoped enums, which prevent the enumerator names from polluting the global namespace 

enum class BlockID {
    BLOCK_ID_23 = 23,
    BLOCK_ID_24 = 24,
    BLOCK_ID_33 = 33,
    BLOCK_ID_36 = 36,
    BLOCK_ID_37 = 37,
    BLOCK_ID_38 = 38,
    BLOCK_ID_39 = 39,
    BLOCK_ID_40 = 40
}

2024-11-20 14:28 UTC, ojayanth commented on src/main.cpp
> +    /* TODO: Enable PLDM : Create rasManagerObj pointer
Either you should report build failure or Log error message saying support is not available till PLDM support is in place . This code can messup , when user enabled PLDM falg.

2024-11-20 14:28 UTC, ojayanth commented on src/main.cpp
> +
Include Boost specific Heder here 
#include <sdbusplus/asio/connection.hpp>
#include <sdbusplus/asio/object_server.hpp>
#include <boost/asio/io_context.hpp>

2024-11-20 16:52 UTC, supven01 requested changes

2024-11-20 16:52 UTC, supven01 commented on OWNERS
> +owners:
Missing. Add your's and Jayanth's name

2024-11-20 16:52 UTC, supven01 commented on OWNERS
> +reviewers:
Add me as Reviewer

2024-11-20 16:52 UTC, supven01 commented on LICENSE
> +                                 Apache License
Apache licensing is fine as we have used that before.

2024-11-20 16:52 UTC, supven01 commented on inc/ras.hpp
> +static const int MI300A_MODEL_NUMBER = 0x90;
This does not belong in generic ras.hpp file. Need a platform file to define this

2024-11-20 16:52 UTC, supven01 commented on inc/ras.hpp
> +static const int TWO_SOCKET = 2;
This does not belong in generic ras.hpp file. Need a platform file to define this

2024-11-20 16:52 UTC, supven01 commented on inc/ras.hpp
> +static const int MI300C_MODEL_NUMBER = 0x80;
This does not belong in generic ras.hpp file. Need a platform file to define this

2024-11-20 16:52 UTC, supven01 commented on inc/ras.hpp
> +static const int TURIN_FAMILY_ID = 0x1A;
This does not belong in generic ras.hpp file. Need a platform file to define this

2024-11-20 16:52 UTC, supven01 commented on inc/ras.hpp
> +static const int GENOA_FAMILY_ID = 0x19;
This does not belong in generic ras.hpp file. Need a platform file to define this

2024-11-20 16:52 UTC, supven01 commented on inc/ras.hpp
> +static const int EPYC_PROG_SEG_ID = 0x01;
This does not belong in generic ras.hpp file. Need a platform file to define this.

2024-11-20 16:52 UTC, supven01 commented on inc/ras.hpp
> +static const int MI_PROG_SEG_ID = 0x02;
This does not belong in generic ras.hpp file. Need a platform file to define this

2024-11-21 10:33 UTC, abinayaddhandapani commented on OWNERS
> +#OWNERS
Updated the README section

2024-11-21 10:34 UTC, abinayaddhandapani commented on LICENSE
> +Full Description:
Supreeth agreed to go with Apache licensing . Updated the latest Apache licensing file from the Upstream

2024-11-21 11:44 UTC, abinayaddhandapani commented on config/ras-config.json
> +{
Added prettier yaml file

2024-11-21 11:45 UTC, abinayaddhandapani commented on meson.build
> +  dependency('libgpiodcxx', default_options: ['bindings=cxx']),
Ack

2024-11-21 11:46 UTC, abinayaddhandapani commented on meson.build
> +  'amd-bmc-ras',
amd-bmc-ras seems to be more suitable for the application. Few more options would be ADDC, amd-crashdump. 
If you have any better suggestion , please suggest

2024-11-21 11:46 UTC, abinayaddhandapani commented on meson.build
> +  'src/main.cpp',
Ack

2024-11-21 11:46 UTC, abinayaddhandapani commented on meson_options.txt
> +option(
Ack

2024-11-21 11:46 UTC, abinayaddhandapani commented on inc/ras.hpp
> +static const int RESERVED = 0;
Ack

2024-11-21 11:46 UTC, abinayaddhandapani commented on inc/ras.hpp
> +        0x61fa3fac, 0xcb80, 0x4292,                                            \
Ack

2024-11-21 11:46 UTC, abinayaddhandapani commented on inc/ras.hpp
> +static const int MI300A_MODEL_NUMBER = 0x90;
Ack

2024-11-21 11:47 UTC, abinayaddhandapani commented on src/main.cpp
> +/**
Ack

2024-11-21 11:47 UTC, abinayaddhandapani commented on src/main.cpp
> +    /* TODO: Enable PLDM : Create rasManagerObj pointer
Ack

2024-11-21 11:47 UTC, abinayaddhandapani commented on src/main.cpp
> +
Ack

2024-11-21 11:47 UTC, abinayaddhandapani commented on OWNERS
> +owners:
Ack

2024-11-21 11:47 UTC, abinayaddhandapani commented on OWNERS
> +reviewers:
Ack

2024-11-21 11:47 UTC, abinayaddhandapani commented on inc/ras.hpp
> +static const int MI300A_MODEL_NUMBER = 0x90;
Ack

2024-11-21 11:47 UTC, abinayaddhandapani commented on inc/ras.hpp
> +static const int MI300C_MODEL_NUMBER = 0x80;
Ack

2024-11-21 11:47 UTC, abinayaddhandapani commented on inc/ras.hpp
> +static const int TURIN_FAMILY_ID = 0x1A;
Ack

2024-11-21 11:48 UTC, abinayaddhandapani commented on inc/ras.hpp
> +static const int GENOA_FAMILY_ID = 0x19;
Ack

2024-11-21 11:51 UTC, abinayaddhandapani commented on meson.build
> +deps = [
Added boost to dependency

2024-11-22 14:10 UTC, ojayanth requested changes
Looks like still missing Key reveiw comments from previosu reveiws , can you please look my comments and respond with your plan , like ack/reject ?

2024-11-22 14:10 UTC, ojayanth commented on config/ras_config.json
> +                    "null",
what is null indicates here?

2024-11-22 14:10 UTC, ojayanth commented on inc/ras.hpp
> +static const int MI300A_MODEL_NUMBER = 0x90;
still Not seeing commit message updated with tested field.

2024-11-22 14:10 UTC, ojayanth commented on inc/interface_manager_base.hpp
> +#include "config_manager.hpp"
Not addressed in the latest patch.

2024-11-22 14:10 UTC, ojayanth commented on inc/apml_manager.hpp
> +#include "cper_generator.hpp"
Will continue reveiw Only after addressing all the previous comments related coding style specific.

2024-11-25 13:59 UTC, abinayaddhandapani commented on config/ras_config.json
> +                "MaxBoundLimit": "50"
We should allow max bound limit as 50 as internal validation team may set that as high for some rare case failures and debug it.

2024-11-25 14:00 UTC, abinayaddhandapani commented on config/ras_config.json
> +            "SystemRecovery": {
The RAS twiki page mentions SystemRecovery every wherehttps://twiki.amd.com/twiki/bin/view/SIG/Sp5OobRasSpec.
I hope we should also align with the same naming

2024-11-25 14:02 UTC, abinayaddhandapani commented on config/ras_config.json
> +                "Description": "Reset Signal Type",
Reset signal can be of 2 types - SYS_RST or RSMRST reset. By default it is SYS_RST

2024-11-25 14:03 UTC, abinayaddhandapani commented on config/ras_config.json
> +                    "null",
These are the deafult values [30h, 34h, 28h, 2Ch, 08h, 0Ch, null, null], which specifies an ordered list of 4-byte aligned offsets to compute the failure signature ID

2024-11-25 14:05 UTC, abinayaddhandapani commented on inc/interface_manager_base.hpp
> +#include "config_manager.hpp"
I have added the comments as metioned in the above format wherever possible. 
The comments where added as part of the function declaration in the classes.

2024-11-25 14:06 UTC, abinayaddhandapani commented on config/ras-config.json
> +  "Configuration": [
Ack

2024-11-25 14:11 UTC, abinayaddhandapani commented on inc/ras.hpp
> +static const int MI300A_MODEL_NUMBER = 0x90;
I have added the tested fields to the commit message

2024-11-26 16:15 UTC, ojayanth requested changes
Making some Good progress , still need some more changes to get OPenBMC coding style . Added high level functional comments. Still seeing updated function prologues, . better get organize the code now and you can start fixing the previous comments. Also noticed Not follwing Naming conventions. - refer https://grok.openbmc.org/xref/openbmc/bmcweb/.clang-tidy?r=0771a264#378 for expeceted format.

2024-11-26 16:15 UTC, ojayanth commented on inc/apml_manager.hpp
> +class ApmlInterfaceManager : public RasManagerBase
General: Enable Namespace based Code organization:
OpenBMC code is extensively used Namespaces in C++, a powerful feature for organizing code and preventing name conflicts, especially in large projects. Here’s a detailed look at namespace-based design in C++:  Please refer any of the OpenBMC repo  to see this approach .

Example:

// File: sensor_manager.h
namespace openbmc_project {
    namespace sensor {
        namespace manager {

            class SensorManager {
            public:
                SensorManager();
                void initialize();
            private:
                void readSensorData();
            };

        } // namespace manager
    } // namespace sensor
} // names

2024-11-27 14:25 UTC, ojayanth requested changes

2024-12-02 05:28 UTC, abinayaddhandapani commented on src/apml_manager.cpp
> +constexpr int EPYC_PROG_SEG_ID = 0x01;
Ack.

2024-12-02 05:28 UTC, abinayaddhandapani commented on inc/interface_manager_base.hpp
> +  public:
Ack

2024-12-02 05:28 UTC, abinayaddhandapani commented on inc/interface_manager_base.hpp
> +    virtual ~RasManagerBase();
Ack

2024-12-02 05:28 UTC, abinayaddhandapani commented on inc/interface_manager_base.hpp
> +    CpuId* cpuId;
Ack

2024-12-02 05:29 UTC, abinayaddhandapani commented on src/interface_manager_base.cpp
> +static const std::string COMMAND_BOARD_ID = "/sbin/fw_printenv -n board_id";
Ack

2024-12-02 05:29 UTC, abinayaddhandapani commented on inc/apml_manager.hpp
> +    bool compare_with_bitwise_AND(const uint32_t* values,
Ack

2024-12-02 05:30 UTC, abinayaddhandapani commented on inc/apml_manager.hpp
> +    std::vector<uint32_t> hexstring_to_vector(const std::string& hexString);
Ack

2024-12-02 05:30 UTC, abinayaddhandapani commented on inc/apml_manager.hpp
> +#include "interface_manager_base.hpp"
Ack

2024-12-02 05:30 UTC, abinayaddhandapani commented on inc/cper_generator.hpp
> +  protected:
Ack

2025-02-11 16:50 UTC, closed without merging