Add README, OWNERS, LICENSE , clang-format , prettier files
AMDESE/amd-bmc-ras pull request #99
Opened 2024-11-29 04:36 UTC by abinayaddhandapani

- Added README.md with project overview.
    - Added OWNERS file to define project ownership and contributors.
    - Added LICENSE file to specify project licensing terms.
    - Added clang-18 formatter and prettier

2024-12-01 11:36 UTC, ojayanth commented
@abinayaddhandapani  Can you please add your respond PR #98 that will help to avoid duplicate comments here.

2024-12-02 07:52 UTC, ojayanth requested changes

2024-12-02 07:52 UTC, ojayanth commented on src/config_manager.cpp
> +            throw std::runtime_error("Could not open JSON file");
General: should be return dbus error ?

2024-12-02 07:52 UTC, ojayanth commented on src/config_manager.cpp
> +            if (it != configItem.end())
if (auto it = configItem.find(attribute); it != configItem.end()) {  ?

2024-12-02 07:52 UTC, ojayanth commented on src/config_manager.cpp
> +            lg2::info("Attribute updated successfully");
Better to chang to debug ? Not want too many sucessfull messages.

2024-12-02 07:52 UTC, ojayanth commented on src/config_manager.cpp
> +        lg2::error("Error : {ERROR}", "ERROR", e.what());
dbus error ?

2024-12-02 07:52 UTC, ojayanth commented on src/config_manager.cpp
> +            std::string("cp ") + "/usr/share/ras-config/ras_config.json" + " " +
Can you keep json file defition at Name space scope or Meson? that wilkl help users to modify path if required.

2024-12-02 07:52 UTC, ojayanth commented on src/config_manager.cpp
> +        int result = system(copyCommand.c_str());
Not advised in modern c++, 

if (!fs::exists(configFile)) {
        try {
            fs::copy(defaultConfigPath, configFile);
        } catch (const fs::filesystem_error& e) {
            <<error>
            return;
        }
    }

2024-12-02 07:52 UTC, ojayanth commented on src/config_manager.cpp
> +    nlohmann::json data = nlohmann::json::parse(jsonRead);
should add  error check if (!jsonRead.is_open()) {

2024-12-02 07:52 UTC, ojayanth commented on src/config_manager.cpp
> +    for (const auto& item : data["Configuration"])
How about using this algorithm( not tested) , which simplify

for (const auto& item : data["Configuration"]) {
        if (item.is_object() && item.size() == 1) {
            const auto& key = item.begin().key();
            const auto& obj = item[key];

            std::string description = obj["Description"];
            AttributeValue value;
            int64_t maxBoundValue = 0;

            if (obj["Value"].is_boolean()) {
                value = obj["Value"].get<bool>();
            } else if (obj["Value"].is_string()) {
                value = obj["Value"].get<std::string>();
            } else if (obj["Value"].is_number_integer()) {
                value = obj["Value"].get<int64_t>();
            } else if (obj["Value"].is_array()) {
                value = obj["Value"].get<std::vector<std::string>>();
            } else if (obj["Value"].is_object()) {
                value = obj["Value"].get<std::map<std::string, std::string>>();
            }

            int attributeType = value.index();
            configMap[key] = std::make_tuple(attributeType, description, value, maxBoundValue);
        }
    }

2024-12-02 09:05 UTC, abinayaddhandapani commented on include/config_manager.hpp
> +namespace ras_config
Ack

2024-12-02 09:05 UTC, abinayaddhandapani commented on include/config_manager.hpp
> +class RasConfigManager : public Base
ack

2024-12-02 09:10 UTC, abinayaddhandapani commented on meson.build
> +  'amd-bmc-ras',
Agreed. Will rename to amd-ras-manager everywhere. 
Updated in service file as well.

2024-12-02 10:05 UTC, abinayaddhandapani commented on config/ras_config.json
> +            "SystemRecovery": {
Will add "ValidOptions" field to verify if the given value is correct.
        {
            "SystemRecovery": {
                "Description": "System recovery mode",
                "Value": "NO_RESET",
                "ValidOptions": ["COLD_RESET","WARM_RESET"]
            }
        },

2024-12-02 10:06 UTC, abinayaddhandapani commented on config/ras_config.json
> +        {
Not combining the options so the code will be generic for all the attributes requested.

2024-12-02 10:42 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +        lg2::error("Error : {ERROR}", "ERROR", e.what());
This is journalctrl log. Will add error for dbus

2024-12-02 10:50 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +    for (const auto& item : data["Configuration"])
I am trying to construct rasConfigTable which contains all the datas of the json file.
Since name , description , value all are different types we need to parse it individually and create the tuple. 
Else the table is not getting generated as expected

2024-12-03 04:13 UTC, mahkurap requested changes

2024-12-03 04:13 UTC, mahkurap commented on README.md
> +detected. When a fatal error is detected in the system , SMU responds to
no space between the word and comma.
SMU first time use

2024-12-03 04:13 UTC, mahkurap commented on README.md
> +
See if the following paragraph explains the flow:
The amd-bmc-ras service reads the SBRMI registers over the APML upon the ALERT_L assertion by the SMU. It creates CPER records based on the the MCA/MSR dump. <what happens to the just created CPER record? who are the end users of it?>

Explain the System recovery feature in the next paragraph and how it is related to the just created CPER record? Then describe how the user can configure the recovery action, give a pointer where is is explained. for e.g., configuration section.

2024-12-03 04:13 UTC, mahkurap commented on README.md
> +amd-ras is configured per the
do you mean amd-bmc-ras service?

2024-12-03 04:13 UTC, mahkurap commented on README.md
> +amd-ras is configured per the
how configuration of the service is linked with meson_options.txt? May be you want to mention what all can be configured briefly.

2024-12-03 04:13 UTC, mahkurap commented on README.md
> +[meson build files](https://mesonbuild.com/Build-options.html). Available
link is inactive

2024-12-03 04:13 UTC, mahkurap approved these changes

2024-12-04 09:54 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +            std::string("cp ") + "/usr/share/ras-config/ras_config.json" + " " +
Ack

2024-12-04 09:55 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +        int result = system(copyCommand.c_str());
Ack

2024-12-04 10:23 UTC, abinayaddhandapani commented on README.md
> +RAS capabilities supported by the processors .The application creates error
Ack

2024-12-04 10:23 UTC, abinayaddhandapani commented on README.md
> +The amd - bmc - ras service is intended to discover, configure and exercise OOB
Ack

2024-12-04 10:23 UTC, abinayaddhandapani commented on README.md
> +records from RAS telemetry extracted from the processor over APML.
Ack

2024-12-04 10:31 UTC, abinayaddhandapani commented on README.md
> +amd-ras is configured per the
The meson_options.txt is not added for the initial commit. But the options.txt file will be used to get the compiler flag is the underlying protocol is APML or PLDM to harvest the errors

2024-12-04 10:32 UTC, abinayaddhandapani commented on README.md
> +[meson build files](https://mesonbuild.com/Build-options.html). Available
The link will be active when it is clicked from the repo  https://github.com/AMDESE/amd-bmc-ras/blob/review/README.md and not from the PR link

2024-12-04 10:37 UTC, abinayaddhandapani commented on README.md
> +
Ack

2024-12-05 12:27 UTC, ojayanth requested changes

2024-12-05 12:27 UTC, ojayanth commented on src/config_manager.cpp
> +            fs::create_directories(destDir);
Need to handle exceptions throw here.

2024-12-05 12:27 UTC, ojayanth commented on src/config_manager.cpp
> +        lg2::error("Error: Could not read config file");
should inform user. to act on usecase based error.

2024-12-05 12:27 UTC, ojayanth commented on src/config_manager.cpp
> +    for (const auto& item : data["Configuration"])
Can you share the sdbusplus::common::com::amd::ras::
                    Configuration::AttributeType::xx defeitions?

2024-12-08 07:32 UTC, ojayanth requested changes

2024-12-08 07:32 UTC, ojayanth commented on include/config_manager.hpp
> +
remove space b/w closing brackets , unless clang does it .

2024-12-08 07:32 UTC, ojayanth commented on meson.build
> +config_file = '/var/lib/amd-bmc-ras/ras_config.json'
This should be part meson_options.txtand you can use refer how to handle this https://gerrit.openbmc.org/c/openbmc/phosphor-certificate-manager/+/54947

2024-12-08 07:32 UTC, ojayanth commented on meson.build
> +	dependency('boost'),
Missing from previous reveiw

2024-12-08 07:32 UTC, ojayanth commented on meson.build
> +deps = [
Usually boost get unnecessary overheads on binary size  and other issues . please look bios-settings-mg or other repos, to set required boost build  flags setting , and add relevant here , based on your use cases.

2024-12-08 07:32 UTC, ojayanth commented on meson.build
> +  'src/config_manager.cpp',
This list will grow . please start grouping src files ,  refer any of the upstream meson file.

2024-12-08 07:32 UTC, ojayanth commented on src/config_manager.cpp
> +    nlohmann::json j;
Missing comments from previous review.

2024-12-08 07:32 UTC, ojayanth commented on src/config_manager.cpp
> +    if (!jsonFile.is_open())
two exceptions consecutively, which is not valid. You should throw only one exception. 
Looks like you are missing to address error handling , as we diecussed. 
I will stoip reveiw here , will continue reveiw after you revisted error strategy in better way , as diecusssed.

2024-12-09 04:45 UTC, abinayaddhandapani commented on OWNERS
> +owners:
Ack

2024-12-09 04:47 UTC, abinayaddhandapani commented
@ojayanth  There is no public APML documentation link. APML is defined as part of AMD processor programming reference (PPR)

2024-12-09 05:48 UTC, abinayaddhandapani commented on README.md
> +options are documented in `meson_options.txt`
Ack

2024-12-09 05:54 UTC, abinayaddhandapani commented on include/config_manager.hpp
> + * The class pulls the default values of ras_config.json file
Ack

2024-12-09 06:03 UTC, abinayaddhandapani commented on include/config_manager.hpp
> +     * and throw std::runtime_error exception.
updateConfigToDbus() returns only std::runtime_error as exception whenver there is an error in accessing the config file.
D-Bus error is not needed for this API as this API will not be called as part of the external D-Bus call. 
The API just reads the config file and update the rasConfigTable.

2024-12-09 06:05 UTC, abinayaddhandapani commented on include/config_manager.hpp
> +     * and throw std::runtime_error exception.
I have already added in the inline comments that on failure D-Bus error is logged and std::runtime exception is thrown.

2024-12-09 06:14 UTC, abinayaddhandapani commented on include/config_manager.hpp
> +     *  @return returns the current value of the attribute.
Ack

2024-12-09 06:17 UTC, abinayaddhandapani commented on include/config_manager.hpp
> +     */
throwing std::runime_erro is sufficient for this API when the config file is inacessible. There will be no external D-Bus call for this API.

2024-12-09 06:22 UTC, abinayaddhandapani commented on include/config_manager.hpp
> +
Removed

2024-12-09 06:54 UTC, abinayaddhandapani commented on meson.build
> +config_file = '/var/lib/amd-bmc-ras/ras_config.json'
I have went through multiple upstream repositories and the file path are not part of meson.options but on the meson.build.

Attaching the repos for reference.

1.https://github.com/openbmc/phosphor-bmc-code-mgmt/blob/61c1a8aa917a70bef59f7e72a3f69c778347f03f/meson.build#L61

2. https://github.com/openbmc/openpower-occ-control/blob/37abe9be91df2bb173c9642a2740a425904d7921/meson.build#L24

3. https://github.com/openbmc/phosphor-led-manager/blob/2449cf7b2222ad4bf9d0e3dc71bc0d477c8317f7/meson.build#L16

4. https://github.com/openbmc/phosphor-inventory-manager/blob/d8fba8bec76389c4a21d000fb17b07a9cea3bf0c/meson.build#L17

2024-12-09 06:59 UTC, abinayaddhandapani commented on meson.build
> +deps = [
Ack

2024-12-09 07:02 UTC, abinayaddhandapani commented on meson.build
> +  'src/config_manager.cpp',
Ack

2024-12-09 07:10 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +    nlohmann::json j;
I have observed multiple upstream repo uses single letter variable for nlohmann parsing. 
Pleas refer below repo:

https://github.com/openbmc/phosphor-logging/blob/27311616459b2f2acc56c594b570d7896560d637/log_create_main.cpp#L30
https://github.com/openbmc/phosphor-debug-collector/blob/f7a5bf706448b5434bbd9f5ce537d2b35ef59215/dump_entry.cpp#L88
https://github.com/openbmc/telemetry/blob/b47b7db48c4f883eb191077848d55d96bd884607/src/utils/labeled_tuple.hpp#L162
https://github.com/openbmc/sdbusplus/blob/cd3bf08af911356288ddc999337ec9554bd72863/src/exception.cpp#L217

However, will change the single letter variable

2024-12-09 07:33 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +    if (!jsonFile.is_open())
throwing D-bus error should be fine. I will remove the runtime_error() exception

2024-12-18 07:16 UTC, ojayanth requested changes

2024-12-18 07:16 UTC, ojayanth commented on src/config_manager.cpp
> +        int64_t maxBoundValue = 0;
maxBoundValue should get from json , not seeing any code related to this.

2024-12-18 09:29 UTC, abinayaddhandapani commented on README.md
> +The amd - bmc - ras service is intended to discover, configure and exercise OOB
I have already added the comments for this review to the chat
https://github.com/AMDESE/amd-bmc-ras/pull/99#issuecomment-2526883301

2024-12-19 15:43 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +        fs::path destDir = fs::path(CONFIG_FILE).parent_path();
We have already discussed that we are not going to continue the application if the config_file is not found. 

Hence I am not adding catch block here which doesnt seem to be of much use. 

if I catch the exception, again I need to re-throw to terminate the application

2024-12-19 15:45 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +        throw sdbusplus::xyz::openbmc_project::Common::Error::
Ack

2024-12-19 15:52 UTC, abinayaddhandapani commented on OWNERS
> +  email: jayanth.othayoth@amd.com
Ack

2024-12-19 15:58 UTC, abinayaddhandapani commented on README.md
> +detected. When a fatal error is detected in the system , SMU responds to
Ack

2024-12-19 16:01 UTC, abinayaddhandapani commented on README.md
> +[meson build files](https://mesonbuild.com/Build-options.html). Available
Some of the upstream repo such as bmcweb uses the same naming convention.

Please find the link for reference.

https://github.com/openbmc/bmcweb/blob/deae6a789444debc4724fb6902fc5def299afbee/README.md?plain=1#L52

2024-12-19 16:25 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +        int64_t maxBoundValue = 0;
Ack

2024-12-20 07:09 UTC, ojayanth requested changes

2024-12-20 07:09 UTC, ojayanth commented on src/config_manager.cpp
> +    auto configMap = rasConfigTable();
const  type.

2024-12-20 07:09 UTC, ojayanth commented on src/config_manager.cpp
> +    for (auto& [key, tuple] : configMap)
const auto

2024-12-20 07:09 UTC, ojayanth commented on src/config_manager.cpp
> +                    lg2::error(
add attribute name and value - usefull for debug

2024-12-20 07:09 UTC, ojayanth commented on src/config_manager.cpp
> +                lg2::error("Valid option not provided");
add attribute name /value.

2024-12-20 07:09 UTC, ojayanth commented on src/config_manager.cpp
> +        lg2::error("Attribute not found");
add attribute name .

2024-12-20 19:05 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +        lg2::error("Attribute not found");
Ack

2024-12-20 19:05 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +                lg2::error("Valid option not provided");
Ack

2024-12-20 19:05 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +                    lg2::error(
Ack

2024-12-20 19:05 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +    for (auto& [key, tuple] : configMap)
Ack

2024-12-20 19:05 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +    auto configMap = rasConfigTable();
Ack

2024-12-20 19:06 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +        throw std::runtime_error("Error: Could not read config file");
Ack

2024-12-20 19:06 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +        std::variant<bool, std::string, int64_t, std::vector<std::string>,
Ack

2024-12-20 19:07 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +            }
Ack

2024-12-20 19:07 UTC, abinayaddhandapani commented on src/config_manager.cpp
> +            description = obj["Description"];
Ack

2025-01-17 11:09 UTC, ojayanth approved these changes

2025-01-17 11:09 UTC, ojayanth commented on OWNERS
> +- jayanth.othayoth@amd.com
ojayanth@gmail.com

2025-01-17 11:09 UTC, ojayanth commented on include/config_manager.hpp
> +/*
All files. License section is not required . please check with supreeth

2025-01-20 05:15 UTC, abinayaddhandapani commented on OWNERS
> +- jayanth.othayoth@amd.com
Ack

2025-01-20 05:15 UTC, abinayaddhandapani commented on include/config_manager.hpp
> +/*
Ack

2025-01-21 14:11 UTC, supven01 approved these changes

2025-01-21 14:15 UTC, merged